// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outpost_common1.proto

package com.wolves.outpost.pb;

public interface BaseboardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Baseboard)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string manufacturer = 1;</code>
   */
  java.lang.String getManufacturer();
  /**
   * <code>string manufacturer = 1;</code>
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <code>string model = 2;</code>
   */
  java.lang.String getModel();
  /**
   * <code>string model = 2;</code>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>string version = 3;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 3;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string serialNumber = 4;</code>
   */
  java.lang.String getSerialNumber();
  /**
   * <code>string serialNumber = 4;</code>
   */
  com.google.protobuf.ByteString
      getSerialNumberBytes();
}
