// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outpost_common1.proto

package com.wolves.outpost.pb;

public interface CpuOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Cpu)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string family = 2;</code>
   */
  java.lang.String getFamily();
  /**
   * <code>string family = 2;</code>
   */
  com.google.protobuf.ByteString
      getFamilyBytes();

  /**
   * <code>string model = 3;</code>
   */
  java.lang.String getModel();
  /**
   * <code>string model = 3;</code>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>string vendor = 4;</code>
   */
  java.lang.String getVendor();
  /**
   * <code>string vendor = 4;</code>
   */
  com.google.protobuf.ByteString
      getVendorBytes();

  /**
   * <code>int64 vendorFreq = 5;</code>
   */
  long getVendorFreq();

  /**
   * <code>int32 physicalProcessorCount = 6;</code>
   */
  int getPhysicalProcessorCount();

  /**
   * <code>int32 logicalProcessorCount = 7;</code>
   */
  int getLogicalProcessorCount();

  /**
   * <code>string identifier = 8;</code>
   */
  java.lang.String getIdentifier();
  /**
   * <code>string identifier = 8;</code>
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();

  /**
   * <code>string processorId = 9;</code>
   */
  java.lang.String getProcessorId();
  /**
   * <code>string processorId = 9;</code>
   */
  com.google.protobuf.ByteString
      getProcessorIdBytes();

  /**
   * <code>double systemCpuLoad = 10;</code>
   */
  double getSystemCpuLoad();

  /**
   * <code>double systemUpTime = 11;</code>
   */
  double getSystemUpTime();

  /**
   * <code>.LoadFactor loadFactor = 12;</code>
   */
  boolean hasLoadFactor();
  /**
   * <code>.LoadFactor loadFactor = 12;</code>
   */
  com.wolves.outpost.pb.LoadFactor getLoadFactor();
  /**
   * <code>.LoadFactor loadFactor = 12;</code>
   */
  com.wolves.outpost.pb.LoadFactorOrBuilder getLoadFactorOrBuilder();
}
