// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outpost_common1.proto

package com.wolves.outpost.pb;

public interface FileSystemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileSystem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 openFileDescriptors = 1;</code>
   */
  long getOpenFileDescriptors();

  /**
   * <code>int64 maxFileDescriptors = 2;</code>
   */
  long getMaxFileDescriptors();

  /**
   * <code>repeated .OsFileStore osFileStores = 3;</code>
   */
  java.util.List<com.wolves.outpost.pb.OsFileStore> 
      getOsFileStoresList();
  /**
   * <code>repeated .OsFileStore osFileStores = 3;</code>
   */
  com.wolves.outpost.pb.OsFileStore getOsFileStores(int index);
  /**
   * <code>repeated .OsFileStore osFileStores = 3;</code>
   */
  int getOsFileStoresCount();
  /**
   * <code>repeated .OsFileStore osFileStores = 3;</code>
   */
  java.util.List<? extends com.wolves.outpost.pb.OsFileStoreOrBuilder> 
      getOsFileStoresOrBuilderList();
  /**
   * <code>repeated .OsFileStore osFileStores = 3;</code>
   */
  com.wolves.outpost.pb.OsFileStoreOrBuilder getOsFileStoresOrBuilder(
      int index);
}
