// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outpost_com.proto

package com.wolves.outpost.pb;

public interface GetProcessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetProcessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 orderBy = 1;</code>
   */
  int getOrderBy();

  /**
   * <code>string grepBy = 2;</code>
   */
  java.lang.String getGrepBy();
  /**
   * <code>string grepBy = 2;</code>
   */
  com.google.protobuf.ByteString
      getGrepByBytes();

  /**
   * <code>int32 returnCount = 3;</code>
   */
  int getReturnCount();
}
