// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outpost_common1.proto

package com.wolves.outpost.pb;

public interface MemoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Memory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 total = 1;</code>
   */
  long getTotal();

  /**
   * <code>int64 available = 2;</code>
   */
  long getAvailable();

  /**
   * <code>int64 swapTotal = 3;</code>
   */
  long getSwapTotal();

  /**
   * <code>int64 swapUsed = 4;</code>
   */
  long getSwapUsed();
}
