// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outpost_common1.proto

package com.wolves.outpost.pb;

/**
 * Protobuf type {@code NetworkIf}
 */
public  final class NetworkIf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NetworkIf)
    NetworkIfOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetworkIf.newBuilder() to construct.
  private NetworkIf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetworkIf() {
    name_ = "";
    displayName_ = "";
    mac_ = "";
    mtu_ = 0;
    speed_ = 0L;
    ipv4_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    ipv6_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    bytesRecv_ = 0L;
    bytesSent_ = 0L;
    packetsRecv_ = 0L;
    packetsSent_ = 0L;
    inErrors_ = 0L;
    outErrors_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NetworkIf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            displayName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            mac_ = s;
            break;
          }
          case 32: {

            mtu_ = input.readInt32();
            break;
          }
          case 40: {

            speed_ = input.readInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              ipv4_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000020;
            }
            ipv4_.add(s);
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              ipv6_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000040;
            }
            ipv6_.add(s);
            break;
          }
          case 64: {

            bytesRecv_ = input.readInt64();
            break;
          }
          case 72: {

            bytesSent_ = input.readInt64();
            break;
          }
          case 80: {

            packetsRecv_ = input.readInt64();
            break;
          }
          case 88: {

            packetsSent_ = input.readInt64();
            break;
          }
          case 96: {

            inErrors_ = input.readInt64();
            break;
          }
          case 104: {

            outErrors_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        ipv4_ = ipv4_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        ipv6_ = ipv6_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wolves.outpost.pb.OutpostCommon1.internal_static_NetworkIf_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wolves.outpost.pb.OutpostCommon1.internal_static_NetworkIf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wolves.outpost.pb.NetworkIf.class, com.wolves.outpost.pb.NetworkIf.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object displayName_;
  /**
   * <code>string displayName = 2;</code>
   */
  public java.lang.String getDisplayName() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayName_ = s;
      return s;
    }
  }
  /**
   * <code>string displayName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAC_FIELD_NUMBER = 3;
  private volatile java.lang.Object mac_;
  /**
   * <code>string mac = 3;</code>
   */
  public java.lang.String getMac() {
    java.lang.Object ref = mac_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mac_ = s;
      return s;
    }
  }
  /**
   * <code>string mac = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMacBytes() {
    java.lang.Object ref = mac_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mac_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MTU_FIELD_NUMBER = 4;
  private int mtu_;
  /**
   * <code>int32 mtu = 4;</code>
   */
  public int getMtu() {
    return mtu_;
  }

  public static final int SPEED_FIELD_NUMBER = 5;
  private long speed_;
  /**
   * <code>int64 speed = 5;</code>
   */
  public long getSpeed() {
    return speed_;
  }

  public static final int IPV4_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList ipv4_;
  /**
   * <code>repeated string ipv4 = 6;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getIpv4List() {
    return ipv4_;
  }
  /**
   * <code>repeated string ipv4 = 6;</code>
   */
  public int getIpv4Count() {
    return ipv4_.size();
  }
  /**
   * <code>repeated string ipv4 = 6;</code>
   */
  public java.lang.String getIpv4(int index) {
    return ipv4_.get(index);
  }
  /**
   * <code>repeated string ipv4 = 6;</code>
   */
  public com.google.protobuf.ByteString
      getIpv4Bytes(int index) {
    return ipv4_.getByteString(index);
  }

  public static final int IPV6_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList ipv6_;
  /**
   * <code>repeated string ipv6 = 7;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getIpv6List() {
    return ipv6_;
  }
  /**
   * <code>repeated string ipv6 = 7;</code>
   */
  public int getIpv6Count() {
    return ipv6_.size();
  }
  /**
   * <code>repeated string ipv6 = 7;</code>
   */
  public java.lang.String getIpv6(int index) {
    return ipv6_.get(index);
  }
  /**
   * <code>repeated string ipv6 = 7;</code>
   */
  public com.google.protobuf.ByteString
      getIpv6Bytes(int index) {
    return ipv6_.getByteString(index);
  }

  public static final int BYTESRECV_FIELD_NUMBER = 8;
  private long bytesRecv_;
  /**
   * <code>int64 bytesRecv = 8;</code>
   */
  public long getBytesRecv() {
    return bytesRecv_;
  }

  public static final int BYTESSENT_FIELD_NUMBER = 9;
  private long bytesSent_;
  /**
   * <code>int64 bytesSent = 9;</code>
   */
  public long getBytesSent() {
    return bytesSent_;
  }

  public static final int PACKETSRECV_FIELD_NUMBER = 10;
  private long packetsRecv_;
  /**
   * <code>int64 packetsRecv = 10;</code>
   */
  public long getPacketsRecv() {
    return packetsRecv_;
  }

  public static final int PACKETSSENT_FIELD_NUMBER = 11;
  private long packetsSent_;
  /**
   * <code>int64 packetsSent = 11;</code>
   */
  public long getPacketsSent() {
    return packetsSent_;
  }

  public static final int INERRORS_FIELD_NUMBER = 12;
  private long inErrors_;
  /**
   * <code>int64 inErrors = 12;</code>
   */
  public long getInErrors() {
    return inErrors_;
  }

  public static final int OUTERRORS_FIELD_NUMBER = 13;
  private long outErrors_;
  /**
   * <code>int64 outErrors = 13;</code>
   */
  public long getOutErrors() {
    return outErrors_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getDisplayNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, displayName_);
    }
    if (!getMacBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mac_);
    }
    if (mtu_ != 0) {
      output.writeInt32(4, mtu_);
    }
    if (speed_ != 0L) {
      output.writeInt64(5, speed_);
    }
    for (int i = 0; i < ipv4_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ipv4_.getRaw(i));
    }
    for (int i = 0; i < ipv6_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ipv6_.getRaw(i));
    }
    if (bytesRecv_ != 0L) {
      output.writeInt64(8, bytesRecv_);
    }
    if (bytesSent_ != 0L) {
      output.writeInt64(9, bytesSent_);
    }
    if (packetsRecv_ != 0L) {
      output.writeInt64(10, packetsRecv_);
    }
    if (packetsSent_ != 0L) {
      output.writeInt64(11, packetsSent_);
    }
    if (inErrors_ != 0L) {
      output.writeInt64(12, inErrors_);
    }
    if (outErrors_ != 0L) {
      output.writeInt64(13, outErrors_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getDisplayNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, displayName_);
    }
    if (!getMacBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mac_);
    }
    if (mtu_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, mtu_);
    }
    if (speed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, speed_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < ipv4_.size(); i++) {
        dataSize += computeStringSizeNoTag(ipv4_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIpv4List().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < ipv6_.size(); i++) {
        dataSize += computeStringSizeNoTag(ipv6_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIpv6List().size();
    }
    if (bytesRecv_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, bytesRecv_);
    }
    if (bytesSent_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, bytesSent_);
    }
    if (packetsRecv_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, packetsRecv_);
    }
    if (packetsSent_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, packetsSent_);
    }
    if (inErrors_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, inErrors_);
    }
    if (outErrors_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, outErrors_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wolves.outpost.pb.NetworkIf)) {
      return super.equals(obj);
    }
    com.wolves.outpost.pb.NetworkIf other = (com.wolves.outpost.pb.NetworkIf) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getDisplayName()
        .equals(other.getDisplayName());
    result = result && getMac()
        .equals(other.getMac());
    result = result && (getMtu()
        == other.getMtu());
    result = result && (getSpeed()
        == other.getSpeed());
    result = result && getIpv4List()
        .equals(other.getIpv4List());
    result = result && getIpv6List()
        .equals(other.getIpv6List());
    result = result && (getBytesRecv()
        == other.getBytesRecv());
    result = result && (getBytesSent()
        == other.getBytesSent());
    result = result && (getPacketsRecv()
        == other.getPacketsRecv());
    result = result && (getPacketsSent()
        == other.getPacketsSent());
    result = result && (getInErrors()
        == other.getInErrors());
    result = result && (getOutErrors()
        == other.getOutErrors());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DISPLAYNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayName().hashCode();
    hash = (37 * hash) + MAC_FIELD_NUMBER;
    hash = (53 * hash) + getMac().hashCode();
    hash = (37 * hash) + MTU_FIELD_NUMBER;
    hash = (53 * hash) + getMtu();
    hash = (37 * hash) + SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSpeed());
    if (getIpv4Count() > 0) {
      hash = (37 * hash) + IPV4_FIELD_NUMBER;
      hash = (53 * hash) + getIpv4List().hashCode();
    }
    if (getIpv6Count() > 0) {
      hash = (37 * hash) + IPV6_FIELD_NUMBER;
      hash = (53 * hash) + getIpv6List().hashCode();
    }
    hash = (37 * hash) + BYTESRECV_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBytesRecv());
    hash = (37 * hash) + BYTESSENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBytesSent());
    hash = (37 * hash) + PACKETSRECV_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPacketsRecv());
    hash = (37 * hash) + PACKETSSENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPacketsSent());
    hash = (37 * hash) + INERRORS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInErrors());
    hash = (37 * hash) + OUTERRORS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOutErrors());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wolves.outpost.pb.NetworkIf parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolves.outpost.pb.NetworkIf parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolves.outpost.pb.NetworkIf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolves.outpost.pb.NetworkIf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolves.outpost.pb.NetworkIf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolves.outpost.pb.NetworkIf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolves.outpost.pb.NetworkIf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wolves.outpost.pb.NetworkIf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wolves.outpost.pb.NetworkIf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wolves.outpost.pb.NetworkIf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wolves.outpost.pb.NetworkIf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wolves.outpost.pb.NetworkIf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wolves.outpost.pb.NetworkIf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NetworkIf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NetworkIf)
      com.wolves.outpost.pb.NetworkIfOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolves.outpost.pb.OutpostCommon1.internal_static_NetworkIf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolves.outpost.pb.OutpostCommon1.internal_static_NetworkIf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolves.outpost.pb.NetworkIf.class, com.wolves.outpost.pb.NetworkIf.Builder.class);
    }

    // Construct using com.wolves.outpost.pb.NetworkIf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      displayName_ = "";

      mac_ = "";

      mtu_ = 0;

      speed_ = 0L;

      ipv4_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      ipv6_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      bytesRecv_ = 0L;

      bytesSent_ = 0L;

      packetsRecv_ = 0L;

      packetsSent_ = 0L;

      inErrors_ = 0L;

      outErrors_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wolves.outpost.pb.OutpostCommon1.internal_static_NetworkIf_descriptor;
    }

    public com.wolves.outpost.pb.NetworkIf getDefaultInstanceForType() {
      return com.wolves.outpost.pb.NetworkIf.getDefaultInstance();
    }

    public com.wolves.outpost.pb.NetworkIf build() {
      com.wolves.outpost.pb.NetworkIf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wolves.outpost.pb.NetworkIf buildPartial() {
      com.wolves.outpost.pb.NetworkIf result = new com.wolves.outpost.pb.NetworkIf(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.displayName_ = displayName_;
      result.mac_ = mac_;
      result.mtu_ = mtu_;
      result.speed_ = speed_;
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        ipv4_ = ipv4_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.ipv4_ = ipv4_;
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        ipv6_ = ipv6_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.ipv6_ = ipv6_;
      result.bytesRecv_ = bytesRecv_;
      result.bytesSent_ = bytesSent_;
      result.packetsRecv_ = packetsRecv_;
      result.packetsSent_ = packetsSent_;
      result.inErrors_ = inErrors_;
      result.outErrors_ = outErrors_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wolves.outpost.pb.NetworkIf) {
        return mergeFrom((com.wolves.outpost.pb.NetworkIf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wolves.outpost.pb.NetworkIf other) {
      if (other == com.wolves.outpost.pb.NetworkIf.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDisplayName().isEmpty()) {
        displayName_ = other.displayName_;
        onChanged();
      }
      if (!other.getMac().isEmpty()) {
        mac_ = other.mac_;
        onChanged();
      }
      if (other.getMtu() != 0) {
        setMtu(other.getMtu());
      }
      if (other.getSpeed() != 0L) {
        setSpeed(other.getSpeed());
      }
      if (!other.ipv4_.isEmpty()) {
        if (ipv4_.isEmpty()) {
          ipv4_ = other.ipv4_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensureIpv4IsMutable();
          ipv4_.addAll(other.ipv4_);
        }
        onChanged();
      }
      if (!other.ipv6_.isEmpty()) {
        if (ipv6_.isEmpty()) {
          ipv6_ = other.ipv6_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensureIpv6IsMutable();
          ipv6_.addAll(other.ipv6_);
        }
        onChanged();
      }
      if (other.getBytesRecv() != 0L) {
        setBytesRecv(other.getBytesRecv());
      }
      if (other.getBytesSent() != 0L) {
        setBytesSent(other.getBytesSent());
      }
      if (other.getPacketsRecv() != 0L) {
        setPacketsRecv(other.getPacketsRecv());
      }
      if (other.getPacketsSent() != 0L) {
        setPacketsSent(other.getPacketsSent());
      }
      if (other.getInErrors() != 0L) {
        setInErrors(other.getInErrors());
      }
      if (other.getOutErrors() != 0L) {
        setOutErrors(other.getOutErrors());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wolves.outpost.pb.NetworkIf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wolves.outpost.pb.NetworkIf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayName_ = "";
    /**
     * <code>string displayName = 2;</code>
     */
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayName = 2;</code>
     */
    public Builder setDisplayName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayName = 2;</code>
     */
    public Builder clearDisplayName() {
      
      displayName_ = getDefaultInstance().getDisplayName();
      onChanged();
      return this;
    }
    /**
     * <code>string displayName = 2;</code>
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mac_ = "";
    /**
     * <code>string mac = 3;</code>
     */
    public java.lang.String getMac() {
      java.lang.Object ref = mac_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mac_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mac = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMacBytes() {
      java.lang.Object ref = mac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mac = 3;</code>
     */
    public Builder setMac(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mac_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mac = 3;</code>
     */
    public Builder clearMac() {
      
      mac_ = getDefaultInstance().getMac();
      onChanged();
      return this;
    }
    /**
     * <code>string mac = 3;</code>
     */
    public Builder setMacBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mac_ = value;
      onChanged();
      return this;
    }

    private int mtu_ ;
    /**
     * <code>int32 mtu = 4;</code>
     */
    public int getMtu() {
      return mtu_;
    }
    /**
     * <code>int32 mtu = 4;</code>
     */
    public Builder setMtu(int value) {
      
      mtu_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 mtu = 4;</code>
     */
    public Builder clearMtu() {
      
      mtu_ = 0;
      onChanged();
      return this;
    }

    private long speed_ ;
    /**
     * <code>int64 speed = 5;</code>
     */
    public long getSpeed() {
      return speed_;
    }
    /**
     * <code>int64 speed = 5;</code>
     */
    public Builder setSpeed(long value) {
      
      speed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 speed = 5;</code>
     */
    public Builder clearSpeed() {
      
      speed_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList ipv4_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureIpv4IsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        ipv4_ = new com.google.protobuf.LazyStringArrayList(ipv4_);
        bitField0_ |= 0x00000020;
       }
    }
    /**
     * <code>repeated string ipv4 = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIpv4List() {
      return ipv4_.getUnmodifiableView();
    }
    /**
     * <code>repeated string ipv4 = 6;</code>
     */
    public int getIpv4Count() {
      return ipv4_.size();
    }
    /**
     * <code>repeated string ipv4 = 6;</code>
     */
    public java.lang.String getIpv4(int index) {
      return ipv4_.get(index);
    }
    /**
     * <code>repeated string ipv4 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIpv4Bytes(int index) {
      return ipv4_.getByteString(index);
    }
    /**
     * <code>repeated string ipv4 = 6;</code>
     */
    public Builder setIpv4(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIpv4IsMutable();
      ipv4_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv4 = 6;</code>
     */
    public Builder addIpv4(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIpv4IsMutable();
      ipv4_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv4 = 6;</code>
     */
    public Builder addAllIpv4(
        java.lang.Iterable<java.lang.String> values) {
      ensureIpv4IsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ipv4_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv4 = 6;</code>
     */
    public Builder clearIpv4() {
      ipv4_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv4 = 6;</code>
     */
    public Builder addIpv4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureIpv4IsMutable();
      ipv4_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList ipv6_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureIpv6IsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        ipv6_ = new com.google.protobuf.LazyStringArrayList(ipv6_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <code>repeated string ipv6 = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIpv6List() {
      return ipv6_.getUnmodifiableView();
    }
    /**
     * <code>repeated string ipv6 = 7;</code>
     */
    public int getIpv6Count() {
      return ipv6_.size();
    }
    /**
     * <code>repeated string ipv6 = 7;</code>
     */
    public java.lang.String getIpv6(int index) {
      return ipv6_.get(index);
    }
    /**
     * <code>repeated string ipv6 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getIpv6Bytes(int index) {
      return ipv6_.getByteString(index);
    }
    /**
     * <code>repeated string ipv6 = 7;</code>
     */
    public Builder setIpv6(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIpv6IsMutable();
      ipv6_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv6 = 7;</code>
     */
    public Builder addIpv6(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIpv6IsMutable();
      ipv6_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv6 = 7;</code>
     */
    public Builder addAllIpv6(
        java.lang.Iterable<java.lang.String> values) {
      ensureIpv6IsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ipv6_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv6 = 7;</code>
     */
    public Builder clearIpv6() {
      ipv6_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv6 = 7;</code>
     */
    public Builder addIpv6Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureIpv6IsMutable();
      ipv6_.add(value);
      onChanged();
      return this;
    }

    private long bytesRecv_ ;
    /**
     * <code>int64 bytesRecv = 8;</code>
     */
    public long getBytesRecv() {
      return bytesRecv_;
    }
    /**
     * <code>int64 bytesRecv = 8;</code>
     */
    public Builder setBytesRecv(long value) {
      
      bytesRecv_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bytesRecv = 8;</code>
     */
    public Builder clearBytesRecv() {
      
      bytesRecv_ = 0L;
      onChanged();
      return this;
    }

    private long bytesSent_ ;
    /**
     * <code>int64 bytesSent = 9;</code>
     */
    public long getBytesSent() {
      return bytesSent_;
    }
    /**
     * <code>int64 bytesSent = 9;</code>
     */
    public Builder setBytesSent(long value) {
      
      bytesSent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bytesSent = 9;</code>
     */
    public Builder clearBytesSent() {
      
      bytesSent_ = 0L;
      onChanged();
      return this;
    }

    private long packetsRecv_ ;
    /**
     * <code>int64 packetsRecv = 10;</code>
     */
    public long getPacketsRecv() {
      return packetsRecv_;
    }
    /**
     * <code>int64 packetsRecv = 10;</code>
     */
    public Builder setPacketsRecv(long value) {
      
      packetsRecv_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 packetsRecv = 10;</code>
     */
    public Builder clearPacketsRecv() {
      
      packetsRecv_ = 0L;
      onChanged();
      return this;
    }

    private long packetsSent_ ;
    /**
     * <code>int64 packetsSent = 11;</code>
     */
    public long getPacketsSent() {
      return packetsSent_;
    }
    /**
     * <code>int64 packetsSent = 11;</code>
     */
    public Builder setPacketsSent(long value) {
      
      packetsSent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 packetsSent = 11;</code>
     */
    public Builder clearPacketsSent() {
      
      packetsSent_ = 0L;
      onChanged();
      return this;
    }

    private long inErrors_ ;
    /**
     * <code>int64 inErrors = 12;</code>
     */
    public long getInErrors() {
      return inErrors_;
    }
    /**
     * <code>int64 inErrors = 12;</code>
     */
    public Builder setInErrors(long value) {
      
      inErrors_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 inErrors = 12;</code>
     */
    public Builder clearInErrors() {
      
      inErrors_ = 0L;
      onChanged();
      return this;
    }

    private long outErrors_ ;
    /**
     * <code>int64 outErrors = 13;</code>
     */
    public long getOutErrors() {
      return outErrors_;
    }
    /**
     * <code>int64 outErrors = 13;</code>
     */
    public Builder setOutErrors(long value) {
      
      outErrors_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 outErrors = 13;</code>
     */
    public Builder clearOutErrors() {
      
      outErrors_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NetworkIf)
  }

  // @@protoc_insertion_point(class_scope:NetworkIf)
  private static final com.wolves.outpost.pb.NetworkIf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wolves.outpost.pb.NetworkIf();
  }

  public static com.wolves.outpost.pb.NetworkIf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetworkIf>
      PARSER = new com.google.protobuf.AbstractParser<NetworkIf>() {
    public NetworkIf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetworkIf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NetworkIf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetworkIf> getParserForType() {
    return PARSER;
  }

  public com.wolves.outpost.pb.NetworkIf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

