// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outpost_com.proto

package com.wolves.outpost.pb;

public interface PrePushFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrePushFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pushId = 1;</code>
   */
  java.lang.String getPushId();
  /**
   * <code>string pushId = 1;</code>
   */
  com.google.protobuf.ByteString
      getPushIdBytes();
}
