// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outpost_common1.proto

package com.wolves.outpost.pb;

public interface ServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Server)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string manufacturer = 1;</code>
   */
  java.lang.String getManufacturer();
  /**
   * <code>string manufacturer = 1;</code>
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <code>string model = 2;</code>
   */
  java.lang.String getModel();
  /**
   * <code>string model = 2;</code>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>string serialNumber = 3;</code>
   */
  java.lang.String getSerialNumber();
  /**
   * <code>string serialNumber = 3;</code>
   */
  com.google.protobuf.ByteString
      getSerialNumberBytes();

  /**
   * <code>.Baseboard baseboard = 4;</code>
   */
  boolean hasBaseboard();
  /**
   * <code>.Baseboard baseboard = 4;</code>
   */
  com.wolves.outpost.pb.Baseboard getBaseboard();
  /**
   * <code>.Baseboard baseboard = 4;</code>
   */
  com.wolves.outpost.pb.BaseboardOrBuilder getBaseboardOrBuilder();

  /**
   * <code>.Cpu cpu = 5;</code>
   */
  boolean hasCpu();
  /**
   * <code>.Cpu cpu = 5;</code>
   */
  com.wolves.outpost.pb.Cpu getCpu();
  /**
   * <code>.Cpu cpu = 5;</code>
   */
  com.wolves.outpost.pb.CpuOrBuilder getCpuOrBuilder();

  /**
   * <code>.Memory memory = 6;</code>
   */
  boolean hasMemory();
  /**
   * <code>.Memory memory = 6;</code>
   */
  com.wolves.outpost.pb.Memory getMemory();
  /**
   * <code>.Memory memory = 6;</code>
   */
  com.wolves.outpost.pb.MemoryOrBuilder getMemoryOrBuilder();

  /**
   * <code>repeated .HwDiskStore hwDiskStore = 7;</code>
   */
  java.util.List<com.wolves.outpost.pb.HwDiskStore> 
      getHwDiskStoreList();
  /**
   * <code>repeated .HwDiskStore hwDiskStore = 7;</code>
   */
  com.wolves.outpost.pb.HwDiskStore getHwDiskStore(int index);
  /**
   * <code>repeated .HwDiskStore hwDiskStore = 7;</code>
   */
  int getHwDiskStoreCount();
  /**
   * <code>repeated .HwDiskStore hwDiskStore = 7;</code>
   */
  java.util.List<? extends com.wolves.outpost.pb.HwDiskStoreOrBuilder> 
      getHwDiskStoreOrBuilderList();
  /**
   * <code>repeated .HwDiskStore hwDiskStore = 7;</code>
   */
  com.wolves.outpost.pb.HwDiskStoreOrBuilder getHwDiskStoreOrBuilder(
      int index);

  /**
   * <code>repeated .NetworkIf networkIf = 8;</code>
   */
  java.util.List<com.wolves.outpost.pb.NetworkIf> 
      getNetworkIfList();
  /**
   * <code>repeated .NetworkIf networkIf = 8;</code>
   */
  com.wolves.outpost.pb.NetworkIf getNetworkIf(int index);
  /**
   * <code>repeated .NetworkIf networkIf = 8;</code>
   */
  int getNetworkIfCount();
  /**
   * <code>repeated .NetworkIf networkIf = 8;</code>
   */
  java.util.List<? extends com.wolves.outpost.pb.NetworkIfOrBuilder> 
      getNetworkIfOrBuilderList();
  /**
   * <code>repeated .NetworkIf networkIf = 8;</code>
   */
  com.wolves.outpost.pb.NetworkIfOrBuilder getNetworkIfOrBuilder(
      int index);

  /**
   * <code>.Os os = 9;</code>
   */
  boolean hasOs();
  /**
   * <code>.Os os = 9;</code>
   */
  com.wolves.outpost.pb.Os getOs();
  /**
   * <code>.Os os = 9;</code>
   */
  com.wolves.outpost.pb.OsOrBuilder getOsOrBuilder();

  /**
   * <code>int64 updateTime = 10;</code>
   */
  long getUpdateTime();
}
