// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_common.proto

package com.wolves.admin.pb;

public final class AdminCommon {
  private AdminCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InterfaceStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InterfaceStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_File_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_File_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseNodeConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseNodeConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022admin_common.proto\"q\n\nNodeStatus\022\023\n\013co" +
      "llectTime\030\001 \001(\003\022#\n\nnodeStatus\030\002 \001(\0162\017.No" +
      "deStatusEnum\022)\n\017interfaceStatus\030\003 \003(\0132\020." +
      "InterfaceStatus\"u\n\017InterfaceStatus\022\016\n\006ac" +
      "tion\030\001 \001(\t\022\022\n\nactVersion\030\002 \001(\t\022\014\n\004jams\030\003" +
      " \001(\005\022\030\n\020avaiCostsPerMin_\030\004 \001(\005\022\026\n\016avaiHi" +
      "tsPerMin\030\005 \001(\005\"\265\002\n\004Node\022\n\n\002ip\030\001 \001(\t\022\033\n\010p" +
      "rotocol\030\002 \001(\0162\t.Protocol\022\014\n\004port\030\003 \001(\005\022\017" +
      "\n\007ngLabel\030\004 \001(\t\022\021\n\tngVersion\030\005 \001(\t\022\022\n\nre" +
      "cordTime\030\006 \001(\003\022\037\n\nnodeStatus\030\007 \001(\0132\013.Nod",
      "eStatus\022\022\n\nloadFactor\030\010 \001(\005\022\025\n\rserverTim" +
      "eout\030\t \001(\005\022\025\n\rclientTimeout\030\n \001(\005\022\022\n\ncli" +
      "entSize\030\013 \001(\005\022\025\n\rclientSizeMax\030\014 \001(\005\022#\n\n" +
      "nodeConfig\030\r \001(\0132\017.BaseNodeConfig\022\013\n\003pid" +
      "\030\016 \001(\t\"-\n\004File\022\020\n\010fileName\030\001 \001(\t\022\023\n\013file" +
      "Content\030\002 \001(\014\"\340\001\n\016BaseNodeConfig\022\023\n\013serv" +
      "icePort\030\001 \001(\005\022\022\n\nserverSize\030\002 \001(\005\022\025\n\rser" +
      "verSizeMax\030\003 \001(\005\022\025\n\rserverTimeout\030\004 \001(\005\022" +
      "\025\n\rclientTimeout\030\005 \001(\005\022\031\n\021pingAdminInter" +
      "val\030\006 \001(\005\022\033\n\014confFiles3Rd\030\007 \003(\0132\005.File\022\020",
      "\n\010whiteIps\030\010 \003(\t\022\026\n\016messageSizeMax\030\t \001(\005" +
      "\"E\n\tNodeGroup\022\017\n\007ngLabel\030\001 \001(\t\022\021\n\tngVers" +
      "ion\030\002 \001(\t\022\024\n\005nodes\030\003 \003(\0132\005.Node*A\n\016NodeS" +
      "tatusEnum\022\006\n\002NA\020\000\022\007\n\003OFF\020\001\022\013\n\007STANDBY\020\002\022" +
      "\t\n\005READY\020\003\022\006\n\002ON\020\004*\034\n\010Protocol\022\007\n\003TCP\020\000\022" +
      "\007\n\003UDP\020\001B$\n\023com.wolves.admin.pbB\013AdminCo" +
      "mmonP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NodeStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NodeStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeStatus_descriptor,
        new java.lang.String[] { "CollectTime", "NodeStatus", "InterfaceStatus", });
    internal_static_InterfaceStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_InterfaceStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InterfaceStatus_descriptor,
        new java.lang.String[] { "Action", "ActVersion", "Jams", "AvaiCostsPerMin", "AvaiHitsPerMin", });
    internal_static_Node_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Node_descriptor,
        new java.lang.String[] { "Ip", "Protocol", "Port", "NgLabel", "NgVersion", "RecordTime", "NodeStatus", "LoadFactor", "ServerTimeout", "ClientTimeout", "ClientSize", "ClientSizeMax", "NodeConfig", "Pid", });
    internal_static_File_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_File_descriptor,
        new java.lang.String[] { "FileName", "FileContent", });
    internal_static_BaseNodeConfig_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_BaseNodeConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseNodeConfig_descriptor,
        new java.lang.String[] { "ServicePort", "ServerSize", "ServerSizeMax", "ServerTimeout", "ClientTimeout", "PingAdminInterval", "ConfFiles3Rd", "WhiteIps", "MessageSizeMax", });
    internal_static_NodeGroup_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_NodeGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeGroup_descriptor,
        new java.lang.String[] { "NgLabel", "NgVersion", "Nodes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
