// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_com.proto

package com.wolves.admin.pb;

public interface GetServersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetServersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Server servers = 1;</code>
   */
  java.util.List<com.wolves.outpost.pb.Server> 
      getServersList();
  /**
   * <code>repeated .Server servers = 1;</code>
   */
  com.wolves.outpost.pb.Server getServers(int index);
  /**
   * <code>repeated .Server servers = 1;</code>
   */
  int getServersCount();
  /**
   * <code>repeated .Server servers = 1;</code>
   */
  java.util.List<? extends com.wolves.outpost.pb.ServerOrBuilder> 
      getServersOrBuilderList();
  /**
   * <code>repeated .Server servers = 1;</code>
   */
  com.wolves.outpost.pb.ServerOrBuilder getServersOrBuilder(
      int index);
}
