// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_com.proto

package com.wolves.admin.pb;

/**
 * Protobuf type {@code GetServersResponse}
 */
public  final class GetServersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetServersResponse)
    GetServersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetServersResponse.newBuilder() to construct.
  private GetServersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetServersResponse() {
    servers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetServersResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              servers_ = new java.util.ArrayList<com.wolves.outpost.pb.Server>();
              mutable_bitField0_ |= 0x00000001;
            }
            servers_.add(
                input.readMessage(com.wolves.outpost.pb.Server.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        servers_ = java.util.Collections.unmodifiableList(servers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wolves.admin.pb.AdminCom.internal_static_GetServersResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wolves.admin.pb.AdminCom.internal_static_GetServersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wolves.admin.pb.GetServersResponse.class, com.wolves.admin.pb.GetServersResponse.Builder.class);
  }

  public static final int SERVERS_FIELD_NUMBER = 1;
  private java.util.List<com.wolves.outpost.pb.Server> servers_;
  /**
   * <code>repeated .Server servers = 1;</code>
   */
  public java.util.List<com.wolves.outpost.pb.Server> getServersList() {
    return servers_;
  }
  /**
   * <code>repeated .Server servers = 1;</code>
   */
  public java.util.List<? extends com.wolves.outpost.pb.ServerOrBuilder> 
      getServersOrBuilderList() {
    return servers_;
  }
  /**
   * <code>repeated .Server servers = 1;</code>
   */
  public int getServersCount() {
    return servers_.size();
  }
  /**
   * <code>repeated .Server servers = 1;</code>
   */
  public com.wolves.outpost.pb.Server getServers(int index) {
    return servers_.get(index);
  }
  /**
   * <code>repeated .Server servers = 1;</code>
   */
  public com.wolves.outpost.pb.ServerOrBuilder getServersOrBuilder(
      int index) {
    return servers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < servers_.size(); i++) {
      output.writeMessage(1, servers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < servers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, servers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wolves.admin.pb.GetServersResponse)) {
      return super.equals(obj);
    }
    com.wolves.admin.pb.GetServersResponse other = (com.wolves.admin.pb.GetServersResponse) obj;

    boolean result = true;
    result = result && getServersList()
        .equals(other.getServersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getServersCount() > 0) {
      hash = (37 * hash) + SERVERS_FIELD_NUMBER;
      hash = (53 * hash) + getServersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wolves.admin.pb.GetServersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolves.admin.pb.GetServersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolves.admin.pb.GetServersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolves.admin.pb.GetServersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolves.admin.pb.GetServersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolves.admin.pb.GetServersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolves.admin.pb.GetServersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wolves.admin.pb.GetServersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wolves.admin.pb.GetServersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wolves.admin.pb.GetServersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wolves.admin.pb.GetServersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wolves.admin.pb.GetServersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wolves.admin.pb.GetServersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetServersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetServersResponse)
      com.wolves.admin.pb.GetServersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolves.admin.pb.AdminCom.internal_static_GetServersResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolves.admin.pb.AdminCom.internal_static_GetServersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolves.admin.pb.GetServersResponse.class, com.wolves.admin.pb.GetServersResponse.Builder.class);
    }

    // Construct using com.wolves.admin.pb.GetServersResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getServersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (serversBuilder_ == null) {
        servers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        serversBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wolves.admin.pb.AdminCom.internal_static_GetServersResponse_descriptor;
    }

    public com.wolves.admin.pb.GetServersResponse getDefaultInstanceForType() {
      return com.wolves.admin.pb.GetServersResponse.getDefaultInstance();
    }

    public com.wolves.admin.pb.GetServersResponse build() {
      com.wolves.admin.pb.GetServersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wolves.admin.pb.GetServersResponse buildPartial() {
      com.wolves.admin.pb.GetServersResponse result = new com.wolves.admin.pb.GetServersResponse(this);
      int from_bitField0_ = bitField0_;
      if (serversBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          servers_ = java.util.Collections.unmodifiableList(servers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.servers_ = servers_;
      } else {
        result.servers_ = serversBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wolves.admin.pb.GetServersResponse) {
        return mergeFrom((com.wolves.admin.pb.GetServersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wolves.admin.pb.GetServersResponse other) {
      if (other == com.wolves.admin.pb.GetServersResponse.getDefaultInstance()) return this;
      if (serversBuilder_ == null) {
        if (!other.servers_.isEmpty()) {
          if (servers_.isEmpty()) {
            servers_ = other.servers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServersIsMutable();
            servers_.addAll(other.servers_);
          }
          onChanged();
        }
      } else {
        if (!other.servers_.isEmpty()) {
          if (serversBuilder_.isEmpty()) {
            serversBuilder_.dispose();
            serversBuilder_ = null;
            servers_ = other.servers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            serversBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getServersFieldBuilder() : null;
          } else {
            serversBuilder_.addAllMessages(other.servers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wolves.admin.pb.GetServersResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wolves.admin.pb.GetServersResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.wolves.outpost.pb.Server> servers_ =
      java.util.Collections.emptyList();
    private void ensureServersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        servers_ = new java.util.ArrayList<com.wolves.outpost.pb.Server>(servers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wolves.outpost.pb.Server, com.wolves.outpost.pb.Server.Builder, com.wolves.outpost.pb.ServerOrBuilder> serversBuilder_;

    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public java.util.List<com.wolves.outpost.pb.Server> getServersList() {
      if (serversBuilder_ == null) {
        return java.util.Collections.unmodifiableList(servers_);
      } else {
        return serversBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public int getServersCount() {
      if (serversBuilder_ == null) {
        return servers_.size();
      } else {
        return serversBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public com.wolves.outpost.pb.Server getServers(int index) {
      if (serversBuilder_ == null) {
        return servers_.get(index);
      } else {
        return serversBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public Builder setServers(
        int index, com.wolves.outpost.pb.Server value) {
      if (serversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.set(index, value);
        onChanged();
      } else {
        serversBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public Builder setServers(
        int index, com.wolves.outpost.pb.Server.Builder builderForValue) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.set(index, builderForValue.build());
        onChanged();
      } else {
        serversBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public Builder addServers(com.wolves.outpost.pb.Server value) {
      if (serversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.add(value);
        onChanged();
      } else {
        serversBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public Builder addServers(
        int index, com.wolves.outpost.pb.Server value) {
      if (serversBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServersIsMutable();
        servers_.add(index, value);
        onChanged();
      } else {
        serversBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public Builder addServers(
        com.wolves.outpost.pb.Server.Builder builderForValue) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.add(builderForValue.build());
        onChanged();
      } else {
        serversBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public Builder addServers(
        int index, com.wolves.outpost.pb.Server.Builder builderForValue) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.add(index, builderForValue.build());
        onChanged();
      } else {
        serversBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public Builder addAllServers(
        java.lang.Iterable<? extends com.wolves.outpost.pb.Server> values) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, servers_);
        onChanged();
      } else {
        serversBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public Builder clearServers() {
      if (serversBuilder_ == null) {
        servers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        serversBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public Builder removeServers(int index) {
      if (serversBuilder_ == null) {
        ensureServersIsMutable();
        servers_.remove(index);
        onChanged();
      } else {
        serversBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public com.wolves.outpost.pb.Server.Builder getServersBuilder(
        int index) {
      return getServersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public com.wolves.outpost.pb.ServerOrBuilder getServersOrBuilder(
        int index) {
      if (serversBuilder_ == null) {
        return servers_.get(index);  } else {
        return serversBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public java.util.List<? extends com.wolves.outpost.pb.ServerOrBuilder> 
         getServersOrBuilderList() {
      if (serversBuilder_ != null) {
        return serversBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(servers_);
      }
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public com.wolves.outpost.pb.Server.Builder addServersBuilder() {
      return getServersFieldBuilder().addBuilder(
          com.wolves.outpost.pb.Server.getDefaultInstance());
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public com.wolves.outpost.pb.Server.Builder addServersBuilder(
        int index) {
      return getServersFieldBuilder().addBuilder(
          index, com.wolves.outpost.pb.Server.getDefaultInstance());
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public java.util.List<com.wolves.outpost.pb.Server.Builder> 
         getServersBuilderList() {
      return getServersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wolves.outpost.pb.Server, com.wolves.outpost.pb.Server.Builder, com.wolves.outpost.pb.ServerOrBuilder> 
        getServersFieldBuilder() {
      if (serversBuilder_ == null) {
        serversBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wolves.outpost.pb.Server, com.wolves.outpost.pb.Server.Builder, com.wolves.outpost.pb.ServerOrBuilder>(
                servers_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        servers_ = null;
      }
      return serversBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetServersResponse)
  }

  // @@protoc_insertion_point(class_scope:GetServersResponse)
  private static final com.wolves.admin.pb.GetServersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wolves.admin.pb.GetServersResponse();
  }

  public static com.wolves.admin.pb.GetServersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetServersResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetServersResponse>() {
    public GetServersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetServersResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetServersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetServersResponse> getParserForType() {
    return PARSER;
  }

  public com.wolves.admin.pb.GetServersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

