// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_common.proto

package com.wolves.admin.pb;

public interface NodeStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 collectTime = 1;</code>
   */
  long getCollectTime();

  /**
   * <code>.NodeStatusEnum nodeStatus = 2;</code>
   */
  int getNodeStatusValue();
  /**
   * <code>.NodeStatusEnum nodeStatus = 2;</code>
   */
  com.wolves.admin.pb.NodeStatusEnum getNodeStatus();

  /**
   * <code>repeated .InterfaceStatus interfaceStatus = 3;</code>
   */
  java.util.List<com.wolves.admin.pb.InterfaceStatus> 
      getInterfaceStatusList();
  /**
   * <code>repeated .InterfaceStatus interfaceStatus = 3;</code>
   */
  com.wolves.admin.pb.InterfaceStatus getInterfaceStatus(int index);
  /**
   * <code>repeated .InterfaceStatus interfaceStatus = 3;</code>
   */
  int getInterfaceStatusCount();
  /**
   * <code>repeated .InterfaceStatus interfaceStatus = 3;</code>
   */
  java.util.List<? extends com.wolves.admin.pb.InterfaceStatusOrBuilder> 
      getInterfaceStatusOrBuilderList();
  /**
   * <code>repeated .InterfaceStatus interfaceStatus = 3;</code>
   */
  com.wolves.admin.pb.InterfaceStatusOrBuilder getInterfaceStatusOrBuilder(
      int index);
}
