// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_store.proto

package com.wolves.admin.pb;

/**
 * Protobuf type {@code NodeHistory}
 */
public  final class NodeHistory extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NodeHistory)
    NodeHistoryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NodeHistory.newBuilder() to construct.
  private NodeHistory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NodeHistory() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NodeHistory(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.wolves.admin.pb.Node.Builder subBuilder = null;
            if (sysNode_ != null) {
              subBuilder = sysNode_.toBuilder();
            }
            sysNode_ = input.readMessage(com.wolves.admin.pb.Node.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sysNode_);
              sysNode_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.wolves.admin.pb.NodeStatus.Builder subBuilder = null;
            if (sysNodeStatus_ != null) {
              subBuilder = sysNodeStatus_.toBuilder();
            }
            sysNodeStatus_ = input.readMessage(com.wolves.admin.pb.NodeStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sysNodeStatus_);
              sysNodeStatus_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wolves.admin.pb.AdminStore.internal_static_NodeHistory_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wolves.admin.pb.AdminStore.internal_static_NodeHistory_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wolves.admin.pb.NodeHistory.class, com.wolves.admin.pb.NodeHistory.Builder.class);
  }

  public static final int SYSNODE_FIELD_NUMBER = 1;
  private com.wolves.admin.pb.Node sysNode_;
  /**
   * <code>.Node sysNode = 1;</code>
   */
  public boolean hasSysNode() {
    return sysNode_ != null;
  }
  /**
   * <code>.Node sysNode = 1;</code>
   */
  public com.wolves.admin.pb.Node getSysNode() {
    return sysNode_ == null ? com.wolves.admin.pb.Node.getDefaultInstance() : sysNode_;
  }
  /**
   * <code>.Node sysNode = 1;</code>
   */
  public com.wolves.admin.pb.NodeOrBuilder getSysNodeOrBuilder() {
    return getSysNode();
  }

  public static final int SYSNODESTATUS_FIELD_NUMBER = 2;
  private com.wolves.admin.pb.NodeStatus sysNodeStatus_;
  /**
   * <code>.NodeStatus sysNodeStatus = 2;</code>
   */
  public boolean hasSysNodeStatus() {
    return sysNodeStatus_ != null;
  }
  /**
   * <code>.NodeStatus sysNodeStatus = 2;</code>
   */
  public com.wolves.admin.pb.NodeStatus getSysNodeStatus() {
    return sysNodeStatus_ == null ? com.wolves.admin.pb.NodeStatus.getDefaultInstance() : sysNodeStatus_;
  }
  /**
   * <code>.NodeStatus sysNodeStatus = 2;</code>
   */
  public com.wolves.admin.pb.NodeStatusOrBuilder getSysNodeStatusOrBuilder() {
    return getSysNodeStatus();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sysNode_ != null) {
      output.writeMessage(1, getSysNode());
    }
    if (sysNodeStatus_ != null) {
      output.writeMessage(2, getSysNodeStatus());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sysNode_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSysNode());
    }
    if (sysNodeStatus_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSysNodeStatus());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wolves.admin.pb.NodeHistory)) {
      return super.equals(obj);
    }
    com.wolves.admin.pb.NodeHistory other = (com.wolves.admin.pb.NodeHistory) obj;

    boolean result = true;
    result = result && (hasSysNode() == other.hasSysNode());
    if (hasSysNode()) {
      result = result && getSysNode()
          .equals(other.getSysNode());
    }
    result = result && (hasSysNodeStatus() == other.hasSysNodeStatus());
    if (hasSysNodeStatus()) {
      result = result && getSysNodeStatus()
          .equals(other.getSysNodeStatus());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSysNode()) {
      hash = (37 * hash) + SYSNODE_FIELD_NUMBER;
      hash = (53 * hash) + getSysNode().hashCode();
    }
    if (hasSysNodeStatus()) {
      hash = (37 * hash) + SYSNODESTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getSysNodeStatus().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wolves.admin.pb.NodeHistory parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolves.admin.pb.NodeHistory parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolves.admin.pb.NodeHistory parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolves.admin.pb.NodeHistory parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolves.admin.pb.NodeHistory parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wolves.admin.pb.NodeHistory parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wolves.admin.pb.NodeHistory parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wolves.admin.pb.NodeHistory parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wolves.admin.pb.NodeHistory parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wolves.admin.pb.NodeHistory parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wolves.admin.pb.NodeHistory parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wolves.admin.pb.NodeHistory parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wolves.admin.pb.NodeHistory prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NodeHistory}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NodeHistory)
      com.wolves.admin.pb.NodeHistoryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolves.admin.pb.AdminStore.internal_static_NodeHistory_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolves.admin.pb.AdminStore.internal_static_NodeHistory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolves.admin.pb.NodeHistory.class, com.wolves.admin.pb.NodeHistory.Builder.class);
    }

    // Construct using com.wolves.admin.pb.NodeHistory.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (sysNodeBuilder_ == null) {
        sysNode_ = null;
      } else {
        sysNode_ = null;
        sysNodeBuilder_ = null;
      }
      if (sysNodeStatusBuilder_ == null) {
        sysNodeStatus_ = null;
      } else {
        sysNodeStatus_ = null;
        sysNodeStatusBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wolves.admin.pb.AdminStore.internal_static_NodeHistory_descriptor;
    }

    public com.wolves.admin.pb.NodeHistory getDefaultInstanceForType() {
      return com.wolves.admin.pb.NodeHistory.getDefaultInstance();
    }

    public com.wolves.admin.pb.NodeHistory build() {
      com.wolves.admin.pb.NodeHistory result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.wolves.admin.pb.NodeHistory buildPartial() {
      com.wolves.admin.pb.NodeHistory result = new com.wolves.admin.pb.NodeHistory(this);
      if (sysNodeBuilder_ == null) {
        result.sysNode_ = sysNode_;
      } else {
        result.sysNode_ = sysNodeBuilder_.build();
      }
      if (sysNodeStatusBuilder_ == null) {
        result.sysNodeStatus_ = sysNodeStatus_;
      } else {
        result.sysNodeStatus_ = sysNodeStatusBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wolves.admin.pb.NodeHistory) {
        return mergeFrom((com.wolves.admin.pb.NodeHistory)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wolves.admin.pb.NodeHistory other) {
      if (other == com.wolves.admin.pb.NodeHistory.getDefaultInstance()) return this;
      if (other.hasSysNode()) {
        mergeSysNode(other.getSysNode());
      }
      if (other.hasSysNodeStatus()) {
        mergeSysNodeStatus(other.getSysNodeStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wolves.admin.pb.NodeHistory parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wolves.admin.pb.NodeHistory) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.wolves.admin.pb.Node sysNode_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wolves.admin.pb.Node, com.wolves.admin.pb.Node.Builder, com.wolves.admin.pb.NodeOrBuilder> sysNodeBuilder_;
    /**
     * <code>.Node sysNode = 1;</code>
     */
    public boolean hasSysNode() {
      return sysNodeBuilder_ != null || sysNode_ != null;
    }
    /**
     * <code>.Node sysNode = 1;</code>
     */
    public com.wolves.admin.pb.Node getSysNode() {
      if (sysNodeBuilder_ == null) {
        return sysNode_ == null ? com.wolves.admin.pb.Node.getDefaultInstance() : sysNode_;
      } else {
        return sysNodeBuilder_.getMessage();
      }
    }
    /**
     * <code>.Node sysNode = 1;</code>
     */
    public Builder setSysNode(com.wolves.admin.pb.Node value) {
      if (sysNodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sysNode_ = value;
        onChanged();
      } else {
        sysNodeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Node sysNode = 1;</code>
     */
    public Builder setSysNode(
        com.wolves.admin.pb.Node.Builder builderForValue) {
      if (sysNodeBuilder_ == null) {
        sysNode_ = builderForValue.build();
        onChanged();
      } else {
        sysNodeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Node sysNode = 1;</code>
     */
    public Builder mergeSysNode(com.wolves.admin.pb.Node value) {
      if (sysNodeBuilder_ == null) {
        if (sysNode_ != null) {
          sysNode_ =
            com.wolves.admin.pb.Node.newBuilder(sysNode_).mergeFrom(value).buildPartial();
        } else {
          sysNode_ = value;
        }
        onChanged();
      } else {
        sysNodeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Node sysNode = 1;</code>
     */
    public Builder clearSysNode() {
      if (sysNodeBuilder_ == null) {
        sysNode_ = null;
        onChanged();
      } else {
        sysNode_ = null;
        sysNodeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Node sysNode = 1;</code>
     */
    public com.wolves.admin.pb.Node.Builder getSysNodeBuilder() {
      
      onChanged();
      return getSysNodeFieldBuilder().getBuilder();
    }
    /**
     * <code>.Node sysNode = 1;</code>
     */
    public com.wolves.admin.pb.NodeOrBuilder getSysNodeOrBuilder() {
      if (sysNodeBuilder_ != null) {
        return sysNodeBuilder_.getMessageOrBuilder();
      } else {
        return sysNode_ == null ?
            com.wolves.admin.pb.Node.getDefaultInstance() : sysNode_;
      }
    }
    /**
     * <code>.Node sysNode = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wolves.admin.pb.Node, com.wolves.admin.pb.Node.Builder, com.wolves.admin.pb.NodeOrBuilder> 
        getSysNodeFieldBuilder() {
      if (sysNodeBuilder_ == null) {
        sysNodeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wolves.admin.pb.Node, com.wolves.admin.pb.Node.Builder, com.wolves.admin.pb.NodeOrBuilder>(
                getSysNode(),
                getParentForChildren(),
                isClean());
        sysNode_ = null;
      }
      return sysNodeBuilder_;
    }

    private com.wolves.admin.pb.NodeStatus sysNodeStatus_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wolves.admin.pb.NodeStatus, com.wolves.admin.pb.NodeStatus.Builder, com.wolves.admin.pb.NodeStatusOrBuilder> sysNodeStatusBuilder_;
    /**
     * <code>.NodeStatus sysNodeStatus = 2;</code>
     */
    public boolean hasSysNodeStatus() {
      return sysNodeStatusBuilder_ != null || sysNodeStatus_ != null;
    }
    /**
     * <code>.NodeStatus sysNodeStatus = 2;</code>
     */
    public com.wolves.admin.pb.NodeStatus getSysNodeStatus() {
      if (sysNodeStatusBuilder_ == null) {
        return sysNodeStatus_ == null ? com.wolves.admin.pb.NodeStatus.getDefaultInstance() : sysNodeStatus_;
      } else {
        return sysNodeStatusBuilder_.getMessage();
      }
    }
    /**
     * <code>.NodeStatus sysNodeStatus = 2;</code>
     */
    public Builder setSysNodeStatus(com.wolves.admin.pb.NodeStatus value) {
      if (sysNodeStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sysNodeStatus_ = value;
        onChanged();
      } else {
        sysNodeStatusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.NodeStatus sysNodeStatus = 2;</code>
     */
    public Builder setSysNodeStatus(
        com.wolves.admin.pb.NodeStatus.Builder builderForValue) {
      if (sysNodeStatusBuilder_ == null) {
        sysNodeStatus_ = builderForValue.build();
        onChanged();
      } else {
        sysNodeStatusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.NodeStatus sysNodeStatus = 2;</code>
     */
    public Builder mergeSysNodeStatus(com.wolves.admin.pb.NodeStatus value) {
      if (sysNodeStatusBuilder_ == null) {
        if (sysNodeStatus_ != null) {
          sysNodeStatus_ =
            com.wolves.admin.pb.NodeStatus.newBuilder(sysNodeStatus_).mergeFrom(value).buildPartial();
        } else {
          sysNodeStatus_ = value;
        }
        onChanged();
      } else {
        sysNodeStatusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.NodeStatus sysNodeStatus = 2;</code>
     */
    public Builder clearSysNodeStatus() {
      if (sysNodeStatusBuilder_ == null) {
        sysNodeStatus_ = null;
        onChanged();
      } else {
        sysNodeStatus_ = null;
        sysNodeStatusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.NodeStatus sysNodeStatus = 2;</code>
     */
    public com.wolves.admin.pb.NodeStatus.Builder getSysNodeStatusBuilder() {
      
      onChanged();
      return getSysNodeStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.NodeStatus sysNodeStatus = 2;</code>
     */
    public com.wolves.admin.pb.NodeStatusOrBuilder getSysNodeStatusOrBuilder() {
      if (sysNodeStatusBuilder_ != null) {
        return sysNodeStatusBuilder_.getMessageOrBuilder();
      } else {
        return sysNodeStatus_ == null ?
            com.wolves.admin.pb.NodeStatus.getDefaultInstance() : sysNodeStatus_;
      }
    }
    /**
     * <code>.NodeStatus sysNodeStatus = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wolves.admin.pb.NodeStatus, com.wolves.admin.pb.NodeStatus.Builder, com.wolves.admin.pb.NodeStatusOrBuilder> 
        getSysNodeStatusFieldBuilder() {
      if (sysNodeStatusBuilder_ == null) {
        sysNodeStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wolves.admin.pb.NodeStatus, com.wolves.admin.pb.NodeStatus.Builder, com.wolves.admin.pb.NodeStatusOrBuilder>(
                getSysNodeStatus(),
                getParentForChildren(),
                isClean());
        sysNodeStatus_ = null;
      }
      return sysNodeStatusBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NodeHistory)
  }

  // @@protoc_insertion_point(class_scope:NodeHistory)
  private static final com.wolves.admin.pb.NodeHistory DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wolves.admin.pb.NodeHistory();
  }

  public static com.wolves.admin.pb.NodeHistory getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NodeHistory>
      PARSER = new com.google.protobuf.AbstractParser<NodeHistory>() {
    public NodeHistory parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeHistory(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NodeHistory> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NodeHistory> getParserForType() {
    return PARSER;
  }

  public com.wolves.admin.pb.NodeHistory getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

