// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_common.proto

package com.wolves.admin.pb;

public interface NodeGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ngLabel = 1;</code>
   */
  java.lang.String getNgLabel();
  /**
   * <code>string ngLabel = 1;</code>
   */
  com.google.protobuf.ByteString
      getNgLabelBytes();

  /**
   * <code>string ngVersion = 2;</code>
   */
  java.lang.String getNgVersion();
  /**
   * <code>string ngVersion = 2;</code>
   */
  com.google.protobuf.ByteString
      getNgVersionBytes();

  /**
   * <code>repeated .Node nodes = 3;</code>
   */
  java.util.List<com.wolves.admin.pb.Node> 
      getNodesList();
  /**
   * <code>repeated .Node nodes = 3;</code>
   */
  com.wolves.admin.pb.Node getNodes(int index);
  /**
   * <code>repeated .Node nodes = 3;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .Node nodes = 3;</code>
   */
  java.util.List<? extends com.wolves.admin.pb.NodeOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .Node nodes = 3;</code>
   */
  com.wolves.admin.pb.NodeOrBuilder getNodesOrBuilder(
      int index);
}
