// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_common.proto

package com.wolves.admin.pb;

public interface NodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Node)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>.Protocol protocol = 2;</code>
   */
  int getProtocolValue();
  /**
   * <code>.Protocol protocol = 2;</code>
   */
  com.wolves.admin.pb.Protocol getProtocol();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();

  /**
   * <code>string ngLabel = 4;</code>
   */
  java.lang.String getNgLabel();
  /**
   * <code>string ngLabel = 4;</code>
   */
  com.google.protobuf.ByteString
      getNgLabelBytes();

  /**
   * <code>string ngVersion = 5;</code>
   */
  java.lang.String getNgVersion();
  /**
   * <code>string ngVersion = 5;</code>
   */
  com.google.protobuf.ByteString
      getNgVersionBytes();

  /**
   * <code>int64 recordTime = 6;</code>
   */
  long getRecordTime();

  /**
   * <code>.NodeStatus nodeStatus = 7;</code>
   */
  boolean hasNodeStatus();
  /**
   * <code>.NodeStatus nodeStatus = 7;</code>
   */
  com.wolves.admin.pb.NodeStatus getNodeStatus();
  /**
   * <code>.NodeStatus nodeStatus = 7;</code>
   */
  com.wolves.admin.pb.NodeStatusOrBuilder getNodeStatusOrBuilder();

  /**
   * <code>int32 loadFactor = 8;</code>
   */
  int getLoadFactor();

  /**
   * <code>int32 serverTimeout = 9;</code>
   */
  int getServerTimeout();

  /**
   * <code>int32 clientTimeout = 10;</code>
   */
  int getClientTimeout();

  /**
   * <code>int32 clientSize = 11;</code>
   */
  int getClientSize();

  /**
   * <code>int32 clientSizeMax = 12;</code>
   */
  int getClientSizeMax();

  /**
   * <code>.BaseNodeConfig nodeConfig = 13;</code>
   */
  boolean hasNodeConfig();
  /**
   * <code>.BaseNodeConfig nodeConfig = 13;</code>
   */
  com.wolves.admin.pb.BaseNodeConfig getNodeConfig();
  /**
   * <code>.BaseNodeConfig nodeConfig = 13;</code>
   */
  com.wolves.admin.pb.BaseNodeConfigOrBuilder getNodeConfigOrBuilder();

  /**
   * <code>string pid = 14;</code>
   */
  java.lang.String getPid();
  /**
   * <code>string pid = 14;</code>
   */
  com.google.protobuf.ByteString
      getPidBytes();
}
