// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_com.proto

package com.wolves.admin.pb;

public interface PingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Node node = 1;</code>
   */
  boolean hasNode();
  /**
   * <code>.Node node = 1;</code>
   */
  com.wolves.admin.pb.Node getNode();
  /**
   * <code>.Node node = 1;</code>
   */
  com.wolves.admin.pb.NodeOrBuilder getNodeOrBuilder();
}
