// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_com.proto

package com.wolves.admin.pb;

public interface SetConfigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SetConfigRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ngLabel = 1;</code>
   */
  java.lang.String getNgLabel();
  /**
   * <code>string ngLabel = 1;</code>
   */
  com.google.protobuf.ByteString
      getNgLabelBytes();

  /**
   * <code>string ngVersion = 2;</code>
   */
  java.lang.String getNgVersion();
  /**
   * <code>string ngVersion = 2;</code>
   */
  com.google.protobuf.ByteString
      getNgVersionBytes();

  /**
   * <code>.BaseNodeConfig nodeConfig = 3;</code>
   */
  boolean hasNodeConfig();
  /**
   * <code>.BaseNodeConfig nodeConfig = 3;</code>
   */
  com.wolves.admin.pb.BaseNodeConfig getNodeConfig();
  /**
   * <code>.BaseNodeConfig nodeConfig = 3;</code>
   */
  com.wolves.admin.pb.BaseNodeConfigOrBuilder getNodeConfigOrBuilder();
}
