// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_com.proto

package com.wolves.admin.pb;

public interface WhereIsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WhereIsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Node nodes = 1;</code>
   */
  java.util.List<com.wolves.admin.pb.Node> 
      getNodesList();
  /**
   * <code>repeated .Node nodes = 1;</code>
   */
  com.wolves.admin.pb.Node getNodes(int index);
  /**
   * <code>repeated .Node nodes = 1;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .Node nodes = 1;</code>
   */
  java.util.List<? extends com.wolves.admin.pb.NodeOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .Node nodes = 1;</code>
   */
  com.wolves.admin.pb.NodeOrBuilder getNodesOrBuilder(
      int index);
}
