// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.wolves.framework.pb;

public interface DafPingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DafPingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timeInMs = 1;</code>
   */
  long getTimeInMs();
}
