// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.wolves.framework.pb;

public interface DafRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DafRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ngLabel = 1;</code>
   */
  java.lang.String getNgLabel();
  /**
   * <code>string ngLabel = 1;</code>
   */
  com.google.protobuf.ByteString
      getNgLabelBytes();

  /**
   * <code>string ngVersion = 2;</code>
   */
  java.lang.String getNgVersion();
  /**
   * <code>string ngVersion = 2;</code>
   */
  com.google.protobuf.ByteString
      getNgVersionBytes();

  /**
   * <code>string action = 3;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 3;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string actVersion = 4;</code>
   */
  java.lang.String getActVersion();
  /**
   * <code>string actVersion = 4;</code>
   */
  com.google.protobuf.ByteString
      getActVersionBytes();

  /**
   * <code>string fromNg = 5;</code>
   */
  java.lang.String getFromNg();
  /**
   * <code>string fromNg = 5;</code>
   */
  com.google.protobuf.ByteString
      getFromNgBytes();

  /**
   * <code>string fromNgVersion = 6;</code>
   */
  java.lang.String getFromNgVersion();
  /**
   * <code>string fromNgVersion = 6;</code>
   */
  com.google.protobuf.ByteString
      getFromNgVersionBytes();

  /**
   * <code>string fromIp = 7;</code>
   */
  java.lang.String getFromIp();
  /**
   * <code>string fromIp = 7;</code>
   */
  com.google.protobuf.ByteString
      getFromIpBytes();

  /**
   * <code>.google.protobuf.Any body = 8;</code>
   */
  boolean hasBody();
  /**
   * <code>.google.protobuf.Any body = 8;</code>
   */
  com.google.protobuf.Any getBody();
  /**
   * <code>.google.protobuf.Any body = 8;</code>
   */
  com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
}
