// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.wolves.framework.pb;

public interface TimeStackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TimeStack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ngLabel = 1;</code>
   */
  java.lang.String getNgLabel();
  /**
   * <code>string ngLabel = 1;</code>
   */
  com.google.protobuf.ByteString
      getNgLabelBytes();

  /**
   * <code>string ngVersion = 2;</code>
   */
  java.lang.String getNgVersion();
  /**
   * <code>string ngVersion = 2;</code>
   */
  com.google.protobuf.ByteString
      getNgVersionBytes();

  /**
   * <code>string ip = 3;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 3;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 4;</code>
   */
  int getPort();

  /**
   * <code>string action = 5;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 5;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string actVersion = 6;</code>
   */
  java.lang.String getActVersion();
  /**
   * <code>string actVersion = 6;</code>
   */
  com.google.protobuf.ByteString
      getActVersionBytes();

  /**
   * <code>int64 time = 7;</code>
   */
  long getTime();

  /**
   * <code>repeated .TimeStack children_ = 8;</code>
   */
  java.util.List<com.wolves.framework.pb.TimeStack> 
      getChildrenList();
  /**
   * <code>repeated .TimeStack children_ = 8;</code>
   */
  com.wolves.framework.pb.TimeStack getChildren(int index);
  /**
   * <code>repeated .TimeStack children_ = 8;</code>
   */
  int getChildrenCount();
  /**
   * <code>repeated .TimeStack children_ = 8;</code>
   */
  java.util.List<? extends com.wolves.framework.pb.TimeStackOrBuilder> 
      getChildrenOrBuilderList();
  /**
   * <code>repeated .TimeStack children_ = 8;</code>
   */
  com.wolves.framework.pb.TimeStackOrBuilder getChildrenOrBuilder(
      int index);
}
